export const PLAYER_COLUMN_MAP = {
  GW: "gameweek",
  ID: "fantrax_id",
  Player: "name",
  Team: "team",
  Position: "position",
  FPts: "raw_fantrax_pts",
  GP: "games_played",
  GS: "games_started",
  Min: "minutes_played",
  Ros: "ownership_pct",
  "+/-": "ownership_change",
  G: "goals",
  KP: "key_passes",
  AT: "assists",
  SOT: "shots_on_target",
  TkW: "tackles_won",
  DIS: "dispossessed",
  YC: "yellow_cards",
  RC: "red_cards",
  ACNC: "accurate_crosses",
  Int: "interceptions",
  CLR: "clearances",
  CoS: "dribbles_succeeded",
  BS: "blocked_shots",
  AER: "aerials_won",
  SBON: "subbed_on",
  SBOF: "subbed_off",
  PKM: "penalties_missed",
  PKD: "penalties_drawn",
  OG: "own_goals",
  GAO: "goals_against_outfield",
  CS: "clean_sheet",
} as const;

export const KEEPER_COLUMN_MAP = {
  GW: "gameweek",
  ID: "fantrax_id",
  Player: "name",
  Team: "team",
  Position: "position",
  FPts: "raw_fantrax_pts",
  GP: "games_played",
  GS: "games_started",
  Min: "minutes_played",
  Ros: "ownership_pct",
  "+/-": "ownership_change",
  CS: "clean_sheet",
  GA: "goals_against",
  Sv: "saves",
  YC: "yellow_cards",
  RC: "red_cards",
  PKS: "penalty_saves",
  SBON: "subbed_on",
  SBOF: "subbed_off",
  TkW: "tackles_won",
  DIS: "dispossessed",
  G: "goals",
  KP: "key_passes",
  AT: "assists",
  Int: "interceptions",
  CLR: "clearances",
  CoS: "dribbles_succeeded",
  AER: "aerials_won",
  HCS: "high_claims",
  Sm: "smothers",
  OG: "own_goals",
  SOT: "shots_on_target",
} as const;

export const IGNORE_COLUMNS = ["Opponent", "Status", "RkOv", "FP/G"] as const;
